# This manifest adds a namespace for our performance evaluation
apiVersion: v1
kind: Namespace
metadata:
  name: performanceeval
---
# This manifest adds a service account with admin rights
apiVersion: v1
kind: ServiceAccount
metadata:
  name: performanceeval
  namespace: performanceeval
---
# ToDo add here 
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: performanceeval
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: performanceeval
  namespace: performanceeval
---
# This manifest adds a pod for running the performance evaluation with the Service account above
apiVersion: v1
kind: Pod
metadata:
  name: performanceeval
  namespace: performanceeval
spec:
  serviceAccountName: performanceeval
  containers:
  - name: performanceeval
    image: nyli/eval
    command: ["/bin/sh"]
    args: ["eval_performance.sh", "-b", "results", "-m", "1000", "-c"]
